# Generated by Django 5.0.12 on 2025-05-02 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=200, unique=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('device', 'IoT Device')], default='manual', max_length=10)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('water_intake', models.FloatField(blank=True, null=True)),
                ('mood', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stress', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('steps', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Health.device')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
