# Generated by Django 5.0.12 on 2025-04-22 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Analytics', '0002_analytics_occurrence_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('uncompleted', 'Uncompleted'), ('skipped', 'Skipped')], default='uncompleted', max_length=12)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='Analytics.analytics')),
            ],
        ),
    ]
