# Generated by Django 5.0.12 on 2025-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsoccurrence',
            name='calories_burned',
            field=models.FloatField(blank=True, help_text='Calories burned for this single occurrence', null=True),
        ),
    ]
