# Generated by Django 5.0.12 on 2025-06-08 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, help_text='Portion = multiplier × default serving', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('abbreviation', models.CharField(max_length=10)),
                ('unit_type', models.CharField(choices=[('mass', 'Mass (g, mg, kg)'), ('volume', 'Volume (ml, l)'), ('count', 'Count (each, piece)')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('default_serving_size', models.DecimalField(decimal_places=2, help_text='e.g. 150 for 150 g apple or 1.00 for 1 l milk', max_digits=7)),
                ('calories_per_default', models.DecimalField(decimal_places=2, help_text='kcal for one default serving', max_digits=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Foodcalorie.foodcategory')),
                ('default_serving_unit', models.ForeignKey(limit_choices_to={'unit_type__in': ['mass', 'volume', 'count']}, on_delete=django.db.models.deletion.PROTECT, to='Foodcalorie.unit')),
            ],
        ),
    ]
