# Generated by Django 5.0.12 on 2025-06-08 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodcalorie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], db_index=True, max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Amount in the item’s default unit', max_digits=7)),
                ('calories_consumed', models.DecimalField(decimal_places=2, help_text='kcal for this entry', max_digits=7)),
                ('logged_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Foodcalorie.foodcategory')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Foodcalorie.fooditem')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Foodcalorie.foodsize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_consumptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Consumption',
                'verbose_name_plural': 'Food Consumptions',
                'ordering': ['-logged_at'],
            },
        ),
    ]
