# Generated by Django 5.0.12 on 2025-06-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodcalorie', '0002_foodconsumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodconsumption',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], db_index=True, max_length=10),
        ),
    ]
