# Generated by Django 5.0.12 on 2025-04-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='occurrence_count',
            field=models.IntegerField(default=1),
        ),
    ]
