# Generated by Django 5.0.12 on 2025-03-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('goal_category', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain'), ('Build Muscle', 'Build Muscle'), ('Normal', 'Normal')], max_length=20)),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('calories_burned', models.IntegerField()),
                ('intensity', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=10)),
            ],
            options={
                'db_table': 'exercise_exercise',
            },
        ),
    ]
