# Generated by Django 5.0.12 on 2025-03-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='measurement_type',
            field=models.CharField(choices=[('duration', 'Duration'), ('reps_sets', 'Reps and Sets')], default='duration', max_length=15),
        ),
    ]
