# Generated by Django 5.0.12 on 2025-03-05 20:40

from django.db import migrations

def create_subscription_plans(apps, schema_editor):
    DimSubscriptionPlan = apps.get_model('subscriptions', 'DimSubscriptionPlan')
    plans = [
        {"plan_name": "Basic", "description": "Basic subscription plan", "price": 10.00},
        {"plan_name": "Premium", "description": "Premium subscription plan", "price": 20.00},
        {"plan_name": "Advanced", "description": "Advanced subscription plan", "price": 30.00},
    ]
    for plan_data in plans:
        # Use get_or_create to avoid duplicates if migration runs more than once.
        DimSubscriptionPlan.objects.get_or_create(plan_name=plan_data["plan_name"], defaults=plan_data)

def reverse_subscription_plans(apps, schema_editor):
    DimSubscriptionPlan = apps.get_model('subscription_plan', 'DimSubscriptionPlan')
    DimSubscriptionPlan.objects.filter(plan_name__in=["Basic", "Premium", "Advanced"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(create_subscription_plans, reverse_subscription_plans),
    ]
