# Generated by Django 5.0.12 on 2025-03-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_seed_payment_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
