from django.core.management.base import BaseCommand
from Excercise.models import Exercise


class Command(BaseCommand):
    help = "Populate the Exercise table with categorized exercises"

    def handle(self, *args, **kwargs):
        exercises = [
            {
                "goal_category": "Weight Loss",
                "exercise_name": "Jumping Jacks",
                "age_min": 18,
                "age_max": 35,
                "measurement_type": "duration",
                "duration_minutes": 15,
                "reps": None,
                "sets": None,
                "calories_burned": 120,
                "intensity": "High",
            },
            {
                "goal_category": "Weight Loss",
                "exercise_name": "Mountain Climbers",
                "age_min": 25,
                "age_max": 45,
                "measurement_type": "duration",
                "duration_minutes": 10,
                "reps": None,
                "sets": None,
                "calories_burned": 110,
                "intensity": "High",
            },
            {
                "goal_category": "Build Muscle",
                "exercise_name": "Bench Press",
                "age_min": 18,
                "age_max": 45,
                "measurement_type": "reps_sets",
                "duration_minutes": None,
                "reps": 10,
                "sets": 3,
                "calories_burned": 220,
                "intensity": "High",
            },
            {
                "goal_category": "Build Muscle",
                "exercise_name": "Pull Ups",
                "age_min": 20,
                "age_max": 40,
                "measurement_type": "reps_sets",
                "duration_minutes": None,
                "reps": 8,
                "sets": 3,
                "calories_burned": 150,
                "intensity": "High",
            },
            {
                "goal_category": "Weight Gain",
                "exercise_name": "Deadlift",
                "age_min": 20,
                "age_max": 40,
                "measurement_type": "reps_sets",
                "duration_minutes": None,
                "reps": 6,
                "sets": 3,
                "calories_burned": 200,
                "intensity": "Moderate",
            },
            {
                "goal_category": "Weight Gain",
                "exercise_name": "Leg Press",
                "age_min": 18,
                "age_max": 35,
                "measurement_type": "reps_sets",
                "duration_minutes": None,
                "reps": 10,
                "sets": 3,
                "calories_burned": 180,
                "intensity": "Moderate",
            },
            {
                "goal_category": "Normal",
                "exercise_name": "Walking",
                "age_min": 30,
                "age_max": 60,
                "measurement_type": "duration",
                "duration_minutes": 20,
                "reps": None,
                "sets": None,
                "calories_burned": 80,
                "intensity": "Low",
            },
            {
                "goal_category": "Normal",
                "exercise_name": "Cycling",
                "age_min": 25,
                "age_max": 50,
                "measurement_type": "duration",
                "duration_minutes": 30,
                "reps": None,
                "sets": None,
                "calories_burned": 140,
                "intensity": "Moderate",
            },
            {
                "goal_category": "Weight Loss",
                "exercise_name": "Burpees",
                "age_min": 22,
                "age_max": 38,
                "measurement_type": "reps_sets",
                "duration_minutes": None,
                "reps": 12,
                "sets": 2,
                "calories_burned": 160,
                "intensity": "High",
            },
            {
                "goal_category": "Build Muscle",
                "exercise_name": "Squats",
                "age_min": 18,
                "age_max": 40,
                "measurement_type": "reps_sets",
                "duration_minutes": None,
                "reps": 15,
                "sets": 3,
                "calories_burned": 180,
                "intensity": "Moderate",
            },
        ]

        for ex in exercises:
            Exercise.objects.get_or_create(**ex)

        self.stdout.write(self.style.SUCCESS(" Exercise data populated successfully."))
